from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.cli import build_parser
from app.evidence import markdown_evidence_sections


GENERATED_NOTICE = "Generated by `uv run python scripts/render_docs.py`; do not edit this block."
INDEX_START = "<!-- BEGIN GENERATED: document-index -->"
INDEX_END = "<!-- END GENERATED: document-index -->"


def _load_inventory(repo_root: Path) -> dict[str, object]:
    return json.loads((repo_root / "catalog" / "source-inventory.json").read_text(encoding="utf-8"))


def _load_quarantine(repo_root: Path) -> dict[str, dict[str, object]]:
    data = json.loads((repo_root / "catalog" / "mappings" / "publication-quarantine.json").read_text(encoding="utf-8"))
    return {entry["provider_id"]: entry for entry in data["quarantine"]}


def _escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _year_range(entry: dict[str, object]) -> str:
    years = entry["available_years"]
    start = years.get("start_ad")
    end = years.get("end_ad")
    if start is None and end is None:
        return "unknown"
    if start == end:
        return str(start)
    return f"{start or '?'}–{end or '?'}"


def render_provider_index(repo_root: Path, inventory: dict[str, object]) -> str:
    providers = sorted(inventory["providers"], key=lambda item: item["provider_id"])
    notes_path = repo_root / "docs/providers/notes.md"
    notes = markdown_evidence_sections(notes_path.read_text(encoding="utf-8")) if notes_path.exists() else set()
    quarantine = _load_quarantine(repo_root)
    counts: dict[str, int] = {}
    for provider in providers:
        counts[provider["status"]] = counts.get(provider["status"], 0) + 1
    summary = ", ".join(f"{status}: {counts[status]}" for status in ("covered", "partial", "blocked") if status in counts)
    lines = [
        "# Providers",
        "",
        "This table projects the [reviewed inventory](../../catalog/source-inventory.json) and publication policy. [Source judgment](notes.md) holds provider-specific boundaries and durable exceptions; the [runbook](../operations/runbook.md) owns shared operations.",
        "",
        f"> {GENERATED_NOTICE}",
        "",
        f"Inventory `{inventory['inventory_version']}` was captured on `{inventory['captured_at']}`: {len(providers)} providers ({summary}).",
        "",
        "| Provider | Reviewed status | Available years | Records | Events | Failures | Category | Publication | Official sources |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- | --- | --- |",
    ]
    for provider in providers:
        state = provider["local_state"]
        provider_id = provider["provider_id"]
        label = f"[`{provider_id}`](notes.md#{provider_id})" if provider_id in notes else f"`{provider_id}`"
        if provider.get("source_name"):
            label += f"<br>{_escape_cell(provider['source_name'])}"
        publication = f"quarantined: {quarantine[provider_id]['status']}" if provider_id in quarantine else "site policy"
        sources = " · ".join(f"[{index}]({url})" for index, url in enumerate(provider["official_source_urls"], 1))
        lines.append(
            f"| {label} | {provider['status']} | {_year_range(provider)} | "
            f"{state['normalized_paper_records']} | {state['raw_event_pages']} | {state['sync_failures']} | "
            f"{_escape_cell(provider['exam_category'])} | {publication} | {sources} |"
        )
    lines.extend(
        [
            "",
            "Investigated sources that are not runtime providers are tracked separately in [rejected and deferred sources](rejected-sources.md).",
            "",
        ]
    )
    return "\n".join(lines)


def render_rejected_sources(inventory: dict[str, object]) -> str:
    candidates = sorted(inventory["candidates"], key=lambda item: item["source_id"])
    lines = [
        "# Rejected and deferred sources",
        "",
        "These investigated sources are not registered providers. Promotion to a provider requires the source-proof gates in [add a provider](../contributing/add-a-provider.md).",
        "",
        f"> {GENERATED_NOTICE}",
        "",
        "| Source | Disposition | Available years | Category | Reason |",
        "| --- | --- | --- | --- | --- |",
    ]
    for candidate in candidates:
        lines.append(
            f"| `{candidate['source_id']}` | {candidate['status']} | {_year_range(candidate)} | "
            f"{_escape_cell(candidate['exam_category'])} | {_escape_cell(candidate['status_reason'])} |"
        )
        if candidate["official_source_urls"]:
            lines.append(
                f"| ↳ official source |  |  |  | "
                + "<br>".join(f"[{url}]({url})" for url in candidate["official_source_urls"])
                + " |"
            )
        for restriction in candidate["restrictions"]:
            lines.append(f"| ↳ restriction |  |  |  | {_escape_cell(restriction)} |")
    lines.extend(
        [
            "",
            "The inventory owns dispositions, URLs, and availability. This page intentionally contains no separate candidate status taxonomy.",
            "",
        ]
    )
    return "\n".join(lines)


def _command_rows() -> list[tuple[str, str]]:
    parser = build_parser()
    subparsers_action = next(action for action in parser._actions if action.dest == "command")
    help_by_name = {choice.dest: choice.help for choice in subparsers_action._choices_actions}
    return [(name, help_by_name.get(name, parser.description or "")) for name in subparsers_action.choices]


def render_commands() -> str:
    lines = [
        "# Command reference",
        "",
        "Use `uv run python -m app` for every application command in local documentation. CI may invoke the same module with its provisioned Python directly.",
        "",
        f"> {GENERATED_NOTICE} The command names and summaries come from `app.cli.build_parser()`.",
        "",
        "| Subcommand | Purpose | Help |",
        "| --- | --- | --- |",
    ]
    for command, help_text in _command_rows():
        lines.append(
            f"| `{command}` | {_escape_cell(help_text)} | `uv run python -m app {command} --help` |"
        )
    lines.extend(
        [
            "",
            "For task-oriented sequences, use the [runbook](runbook.md), [workflow guide](workflows.md), and [recovery guide](recovery.md).",
            "",
        ]
    )
    return "\n".join(lines)


def _title(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"^#\s+(.+)$", text, flags=re.MULTILINE)
    return match.group(1).replace("`", "") if match else path.stem.replace("-", " ").title()


def render_document_index(repo_root: Path) -> str:
    docs_root = repo_root / "docs"
    paths = []
    for path in docs_root.rglob("*.md"):
        relative = path.relative_to(docs_root)
        if path == docs_root / "README.md" or relative.parts[0] == "archive":
            continue
        if relative.parts[0] == "providers" and path.name not in {"README.md", "rejected-sources.md", "notes.md"}:
            continue
        paths.append(path)
    lines = [INDEX_START, f"> {GENERATED_NOTICE}", "", "| Document | Purpose |", "| --- | --- |"]
    for path in sorted(paths):
        relative = path.relative_to(docs_root).as_posix()
        lines.append(f"| [`{relative}`]({relative}) | {_escape_cell(_title(path))} |")
    lines.append(INDEX_END)
    return "\n".join(lines)


def _replace_block(text: str, start: str, end: str, replacement: str) -> str:
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), flags=re.DOTALL)
    if not pattern.search(text):
        raise ValueError(f"missing generated block markers: {start} / {end}")
    return pattern.sub(replacement, text, count=1)


def expected_outputs(repo_root: Path) -> dict[Path, str]:
    inventory = _load_inventory(repo_root)
    outputs: dict[Path, str] = {}
    providers_root = repo_root / "docs" / "providers"
    outputs[providers_root / "README.md"] = render_provider_index(repo_root, inventory)
    outputs[providers_root / "rejected-sources.md"] = render_rejected_sources(inventory)
    outputs[repo_root / "docs" / "operations" / "commands.md"] = render_commands()

    docs_readme = repo_root / "docs" / "README.md"
    current_readme = docs_readme.read_text(encoding="utf-8")
    outputs[docs_readme] = _replace_block(current_readme, INDEX_START, INDEX_END, render_document_index(repo_root))
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description="Render documentation owned by executable repository state.")
    parser.add_argument("--repo-root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true", help="Fail if any generated document is stale.")
    args = parser.parse_args()
    stale: list[str] = []
    for path, expected in expected_outputs(args.repo_root).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        stale.append(path.relative_to(args.repo_root).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if stale:
        verb = "stale" if args.check else "rendered"
        print(f"{verb} documentation: {', '.join(stale)}")
        return 1 if args.check else 0
    print("generated documentation is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
